experiment:
  name: "SRGAN"
  seed: 1234
data:
  image_dir: "/root/fastsrgan/input/gt"
  image_dir_lq: "/root/fastsrgan/input/lq"
  numpy_dir: "/root/fastsrgan/numpy/gt"
  numpy_dir_lq: "/root/fastsrgan/numpy/lq"
  lr_image_size: 24
  scale_factor: 1
generator:
  n_filters: 64
  n_layers: 8 
discriminator:
  n_filters: 64
  n_layers: 7
training:
  compiled: true
  pretrain_iterations: 100 
  iterations: 100000
  device: cuda
  log_iter: 200
  checkpoint_iter: 100
  batch_size: 24
  num_workers: 2
  generator_lr: 1e-4
  discriminator_lr: 1e-4

